In [1]:
import pandas as pd
X = pd.read_csv('data/Training Data.csv')
y = pd.read_csv('data/Training Data target.csv')

In [2]:
df = X.merge(y, on="id")

In [3]:
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group
0,69572,6000.0,3/14/2011,Roman,1390,Roman,34.938093,-9.856322,none,0,...,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional
1,8776,0.0,3/6/2013,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional
2,34310,25.0,2/25/2013,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,functional
3,67743,0.0,1/28/2013,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,non functional
4,19728,0.0,7/13/2011,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,functional

In [4]:
df.drop("id", axis=1, inplace= True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59400 entries, 0 to 59399
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   amount_tsh             59400 non-null  float64
 1   date_recorded          59400 non-null  object
 2   funder                 55765 non-null  object
 3   gps_height             59400 non-null  int64
 4   installer              55745 non-null  object
 5   longitude              59400 non-null  float64
 6   latitude               59400 non-null  float64
 7   wpt_name               59400 non-null  object
 8   num_private            59400 non-null  int64
 9   basin                  59400 non-null  object
 10  subvillage             59029 non-null  object
 11  region                 59400 non-null  object
 12  region_code            59400 non-null  int64
 13  district_code          59400 non-null  int64
 14  lga                    59400 non-null  object
 15  ward                   59400 non-null  object
 16  population             59400 non-null  int64
 17  public_meeting         56066 non-null  object
 18  recorded_by            59400 non-null  object
 19  scheme_management      55523 non-null  object
 20  scheme_name            31234 non-null  object
 21  permit                 56344 non-null  object
 22  construction_year      59400 non-null  int64
 23  extraction_type        59400 non-null  object
 24  extraction_type_group  59400 non-null  object
 25  extraction_type_class  59400 non-null  object
 26  management             59400 non-null  object
 27  management_group       59400 non-null  object
 28  payment                59400 non-null  object
 29  payment_type           59400 non-null  object
 30  water_quality          59400 non-null  object
 31  quality_group          59400 non-null  object
 32  quantity               59400 non-null  object
 33  quantity_group         59400 non-null  object
 34  source                 59400 non-null  object
 35  source_type            59400 non-null  object
 36  source_class           59400 non-null  object
 37  waterpoint_type        59400 non-null  object
 38  waterpoint_type_group  59400 non-null  object
 39  status_group           59400 non-null  object
dtypes: float64(3), int64(6), object(31)
memory usage: 18.6+ MB

In [6]:
df['scheme_management'].value_counts()

VWC                 36793
WUG                  5206
Water authority      3153
WUA                  2883
Water Board          2748
Parastatal           1680
Private operator     1063
Company              1061
Other                 766
SWC                    97
Trust                  72
None                    1
Name: scheme_management, dtype: int64

In [7]:
df['scheme_management'].isnull().sum()

3877

In [8]:
df['scheme_name'].value_counts()

K                                   682
None                                644
Borehole                            546
Chalinze wate                       405
M                                   400
                                   ...
Mamire water Supply                   1
Mashati Dispensary  water supply      1
Zimba water supply                    1
Msengoni water supply                 1
Shidere mrimashi water supply         1
Name: scheme_name, Length: 2696, dtype: int64

In [9]:
df['scheme_name'].isnull().sum()

28166

In [10]:
df['permit'].value_counts() #most_frequent

True     38852
False    17492
Name: permit, dtype: int64

In [11]:
df['permit'].isnull().sum()

3056

In [13]:
df['construction_year'].value_counts()

0       20709
2010     2645
2008     2613
2009     2533
2000     2091
2007     1587
2006     1471
2003     1286
2011     1256
2004     1123
2012     1084
2002     1075
1978     1037
1995     1014
2005     1011
1999      979
1998      966
1990      954
1985      945
1980      811
1996      811
1984      779
1982      744
1994      738
1972      708
1974      676
1997      644
1992      640
1993      608
2001      540
1988      521
1983      488
1975      437
1986      434
1976      414
1970      411
1991      324
1989      316
1987      302
1981      238
1977      202
1979      192
1973      184
2013      176
1971      145
1960      102
1967       88
1963       85
1968       77
1969       59
1964       40
1962       30
1961       21
1965       19
1966       17
Name: construction_year, dtype: int64

In [14]:
#Fill in median for nulls values
df['construction_year'] = df['construction_year'].replace(0, (df['construction_year'].median()))

In [15]:
df['construction_year_bins'] = pd.cut(x=df['construction_year'], bins=[1960, 1970, 1980, 1990, 2000, 2010, 2013])

In [16]:
df['construction_year_bins']

0        (1990, 2000]
1        (2000, 2010]
2        (2000, 2010]
3        (1980, 1990]
4        (1980, 1990]
             ...
59395    (1990, 2000]
59396    (1990, 2000]
59397    (1980, 1990]
59398    (1980, 1990]
59399    (2000, 2010]
Name: construction_year_bins, Length: 59400, dtype: category
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2013]]

In [17]:
pd.set_option('display.max_columns', None)

In [18]:
df[df['construction_year'] == 2001]

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,status_group,construction_year_bins
420,10.0,9/3/2013,Giz,813,KILI WATER,37.483264,-3.392584,Kwa Mghanga Mwajabu,0,Pangani,Karamsingi,Kilimanjaro,3,4,Moshi Rural,Kirua Vunjo Kusini,50,True,GeoData Consultants Ltd,WUA,Uchira water users association,True,2001,gravity,gravity,gravity,wua,user-group,pay per bucket,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,functional,"(2000, 2010]"
455,0.0,2/6/2013,Fin Water,306,FIN WATER,38.242246,-11.136034,Kwa Mustapha Rashidi,0,Ruvuma / Southern Coast,Msufini,Mtwara,90,63,Nanyumbu,Napacho,86,True,GeoData Consultants Ltd,VWC,NaN,True,2001,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,salty,salty,insufficient,insufficient,machine dbh,borehole,groundwater,hand pump,hand pump,functional,"(2000, 2010]"
564,200.0,2/23/2011,Peace Cope,1722,DWE,34.986357,-9.088171,Kwa Lameki Nyagawa,0,Rufiji,Madamba,Iringa,11,4,Njombe,Ikuka,40,True,GeoData Consultants Ltd,VWC,Ninga hydram water scheme,False,2001,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe multiple,communal standpipe,non functional,"(2000, 2010]"
706,2000.0,2/26/2013,Snv,775,DWE,36.084839,-10.913883,Kwa Juma Ndauka,0,Ruvuma / Southern Coast,Mbulani,Ruvuma,10,5,Namtumbo,Ligera,360,True,GeoData Consultants Ltd,WUG,NaN,False,2001,swn 80,swn 80,handpump,wug,user-group,pay monthly,monthly,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump,non functional,"(2000, 2010]"
808,200.0,2/23/2011,Peace Cope,1747,DWE,34.992884,-9.096642,Kwa Titusi Mponzi,0,Rufiji,Madamba,Iringa,11,4,Njombe,Ikuka,50,True,GeoData Consultants Ltd,VWC,Ninga hydram water scheme,False,2001,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe multiple,communal standpipe,non functional,"(2000, 2010]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58927,0.0,2/4/2013,Lga,347,LGA,38.906089,-10.933906,Kiosk,0,Ruvuma / Southern Coast,Kadudu,Mtwara,90,33,Masasi,Lipumburu,1,True,GeoData Consultants Ltd,VWC,Lipumburu Water,True,2001,mono,mono,motorpump,vwc,user-group,unknown,unknown,salty,salty,dry,dry,machine dbh,borehole,groundwater,communal standpipe,communal standpipe,non functional,"(2000, 2010]"
59006,600.0,1/27/2013,Msf,771,DWE,29.733902,-4.882006,Kisukari,0,Lake Tanganyika,Simbo A,Kigoma,16,3,Kigoma Rural,Simbo,190,True,GeoData Consultants Ltd,WUG,Mkongoro Two,True,2001,other,other,other,vwc,user-group,pay monthly,monthly,soft,good,enough,enough,shallow well,shallow well,groundwater,other,other,non functional,"(2000, 2010]"
59021,250.0,2/3/2013,Oxfarm,1508,OXFARM,29.810473,-4.527626,Sokoni,0,Lake Tanganyika,Mhinda Kati,Kigoma,16,2,Kigoma Rural,Mkigo,950,True,GeoData Consultants Ltd,Water authority,Mroroma,True,2001,gravity,gravity,gravity,water board,user-group,pay monthly,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe multiple,communal standpipe,non functional,"(2000, 2010]"
59066,0.0,3/4/2011,Amref,67,AMREF,38.960496,-7.423405,Kalia Vyula,0,Rufiji,Changedele,Pwani,60,43,Mkuranga,Mkamba,500,True,GeoData Consultants Ltd,VWC,NaN,False,2001,other,other,other,vwc,user-group,never pay,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,other,other,non functional,"(2000, 2010]"
59071,250.0,2/3/2013,Oxfarm,1513,OXFARM,29.799590,-4.520178,Kwa Damasi,0,Lake Tanganyika,Mbweru,Kigoma,16,2,Kigoma Rural,Mkigo,510,True,GeoData Consultants Ltd,Water authority,Mroroma,True,2001,gravity,gravity,gravity,water board,user-group,pay monthly,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe multiple,communal standpipe,functional needs repair,"(2000, 2010]"

In [19]:
df.drop('construction_year', axis=1, inplace=True)

In [20]:
df['extraction_type'].value_counts()

gravity                      26780
nira/tanira                   8154
other                         6430
submersible                   4764
swn 80                        3670
mono                          2865
india mark ii                 2400
afridev                       1770
ksb                           1415
other - rope pump              451
other - swn 81                 229
windmill                       117
india mark iii                  98
cemo                            90
other - play pump               85
walimi                          48
climax                          32
other - mkulima/shinyanga        2
Name: extraction_type, dtype: int64

In [21]:
df['extraction_type_group'].value_counts()

gravity            26780
nira/tanira         8154
other               6430
submersible         6179
swn 80              3670
mono                2865
india mark ii       2400
afridev             1770
rope pump            451
other handpump       364
other motorpump      122
wind-powered         117
india mark iii        98
Name: extraction_type_group, dtype: int64

In [22]:
df['extraction_type_class'].value_counts()

gravity         26780
handpump        16456
other            6430
submersible      6179
motorpump        2987
rope pump         451
wind-powered      117
Name: extraction_type_class, dtype: int64

In [23]:
df['management'].value_counts()

vwc                 40507
wug                  6515
water board          2933
wua                  2535
private operator     1971
parastatal           1768
water authority       904
other                 844
company               685
unknown               561
other - school         99
trust                  78
Name: management, dtype: int64

In [24]:
df['management_group'].value_counts()

user-group    52490
commercial     3638
parastatal     1768
other           943
unknown         561
Name: management_group, dtype: int64

We dropped the columns that had the same categories and keep the ones that are more intuitive.

In [25]:
df= df.drop(["amount_tsh", "num_private","date_recorded","longitude", "latitude","waterpoint_type_group", "subvillage", "region" , "lga", "ward", "recorded_by", "scheme_management","scheme_name", "extraction_type",
            "extraction_type_group","management_group", "payment", "water_quality","quantity_group", "source_type"], axis=1)